// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/mr.proto

package mr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_mapTaskType    TaskType = 0
	TaskType_reduceTaskType TaskType = 1
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "mapTaskType",
		1: "reduceTaskType",
	}
	TaskType_value = map[string]int32{
		"mapTaskType":    0,
		"reduceTaskType": 1,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mr_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_proto_mr_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mr_proto_rawDescGZIP(), []int{0}
}

type WorkerStatus int32

const (
	WorkerStatus_idleWorker     WorkerStatus = 0
	WorkerStatus_assignedWorker WorkerStatus = 1
	WorkerStatus_workedWorker   WorkerStatus = 2
	WorkerStatus_repliedWorker  WorkerStatus = 3
)

// Enum value maps for WorkerStatus.
var (
	WorkerStatus_name = map[int32]string{
		0: "idleWorker",
		1: "assignedWorker",
		2: "workedWorker",
		3: "repliedWorker",
	}
	WorkerStatus_value = map[string]int32{
		"idleWorker":     0,
		"assignedWorker": 1,
		"workedWorker":   2,
		"repliedWorker":  3,
	}
)

func (x WorkerStatus) Enum() *WorkerStatus {
	p := new(WorkerStatus)
	*p = x
	return p
}

func (x WorkerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mr_proto_enumTypes[1].Descriptor()
}

func (WorkerStatus) Type() protoreflect.EnumType {
	return &file_proto_mr_proto_enumTypes[1]
}

func (x WorkerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStatus.Descriptor instead.
func (WorkerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_mr_proto_rawDescGZIP(), []int{1}
}

type AskTaskArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *AskTaskArgs) Reset() {
	*x = AskTaskArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskTaskArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskTaskArgs) ProtoMessage() {}

func (x *AskTaskArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskTaskArgs.ProtoReflect.Descriptor instead.
func (*AskTaskArgs) Descriptor() ([]byte, []int) {
	return file_proto_mr_proto_rawDescGZIP(), []int{0}
}

func (x *AskTaskArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AskTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NReduce                  int32    `protobuf:"varint,1,opt,name=NReduce,proto3" json:"NReduce,omitempty"`
	TaskType                 TaskType `protobuf:"varint,2,opt,name=TaskType,proto3,enum=mr.proto.TaskType" json:"TaskType,omitempty"`
	InputFile                string   `protobuf:"bytes,3,opt,name=InputFile,proto3" json:"InputFile,omitempty"`
	NumOfMapTask             string   `protobuf:"bytes,4,opt,name=NumOfMapTask,proto3" json:"NumOfMapTask,omitempty"`
	IntermediateFilePathList []string `protobuf:"bytes,5,rep,name=IntermediateFilePathList,proto3" json:"IntermediateFilePathList,omitempty"`
	NumOfReduceTask          string   `protobuf:"bytes,6,opt,name=NumOfReduceTask,proto3" json:"NumOfReduceTask,omitempty"`
	Err                      string   `protobuf:"bytes,7,opt,name=Err,proto3" json:"Err,omitempty"`
}

func (x *AskTaskReply) Reset() {
	*x = AskTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AskTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskTaskReply) ProtoMessage() {}

func (x *AskTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskTaskReply.ProtoReflect.Descriptor instead.
func (*AskTaskReply) Descriptor() ([]byte, []int) {
	return file_proto_mr_proto_rawDescGZIP(), []int{1}
}

func (x *AskTaskReply) GetNReduce() int32 {
	if x != nil {
		return x.NReduce
	}
	return 0
}

func (x *AskTaskReply) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_mapTaskType
}

func (x *AskTaskReply) GetInputFile() string {
	if x != nil {
		return x.InputFile
	}
	return ""
}

func (x *AskTaskReply) GetNumOfMapTask() string {
	if x != nil {
		return x.NumOfMapTask
	}
	return ""
}

func (x *AskTaskReply) GetIntermediateFilePathList() []string {
	if x != nil {
		return x.IntermediateFilePathList
	}
	return nil
}

func (x *AskTaskReply) GetNumOfReduceTask() string {
	if x != nil {
		return x.NumOfReduceTask
	}
	return ""
}

func (x *AskTaskReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type MapTaskArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                       string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	IntermediateFilePathList []string `protobuf:"bytes,2,rep,name=IntermediateFilePathList,proto3" json:"IntermediateFilePathList,omitempty"`
}

func (x *MapTaskArgs) Reset() {
	*x = MapTaskArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapTaskArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTaskArgs) ProtoMessage() {}

func (x *MapTaskArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTaskArgs.ProtoReflect.Descriptor instead.
func (*MapTaskArgs) Descriptor() ([]byte, []int) {
	return file_proto_mr_proto_rawDescGZIP(), []int{2}
}

func (x *MapTaskArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MapTaskArgs) GetIntermediateFilePathList() []string {
	if x != nil {
		return x.IntermediateFilePathList
	}
	return nil
}

type MapTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
}

func (x *MapTaskReply) Reset() {
	*x = MapTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTaskReply) ProtoMessage() {}

func (x *MapTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTaskReply.ProtoReflect.Descriptor instead.
func (*MapTaskReply) Descriptor() ([]byte, []int) {
	return file_proto_mr_proto_rawDescGZIP(), []int{3}
}

func (x *MapTaskReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ReduceTaskArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	OutputFile string `protobuf:"bytes,2,opt,name=OutputFile,proto3" json:"OutputFile,omitempty"`
}

func (x *ReduceTaskArgs) Reset() {
	*x = ReduceTaskArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceTaskArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceTaskArgs) ProtoMessage() {}

func (x *ReduceTaskArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceTaskArgs.ProtoReflect.Descriptor instead.
func (*ReduceTaskArgs) Descriptor() ([]byte, []int) {
	return file_proto_mr_proto_rawDescGZIP(), []int{4}
}

func (x *ReduceTaskArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReduceTaskArgs) GetOutputFile() string {
	if x != nil {
		return x.OutputFile
	}
	return ""
}

type ReduceTaskReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
}

func (x *ReduceTaskReply) Reset() {
	*x = ReduceTaskReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReduceTaskReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceTaskReply) ProtoMessage() {}

func (x *ReduceTaskReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceTaskReply.ProtoReflect.Descriptor instead.
func (*ReduceTaskReply) Descriptor() ([]byte, []int) {
	return file_proto_mr_proto_rawDescGZIP(), []int{5}
}

func (x *ReduceTaskReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type HeartbeatArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Now *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Now,proto3" json:"Now,omitempty"`
}

func (x *HeartbeatArgs) Reset() {
	*x = HeartbeatArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatArgs) ProtoMessage() {}

func (x *HeartbeatArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatArgs.ProtoReflect.Descriptor instead.
func (*HeartbeatArgs) Descriptor() ([]byte, []int) {
	return file_proto_mr_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HeartbeatArgs) GetNow() *timestamppb.Timestamp {
	if x != nil {
		return x.Now
	}
	return nil
}

type HeartbeatReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_mr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_proto_mr_proto_rawDescGZIP(), []int{7}
}

var File_proto_mr_proto protoreflect.FileDescriptor

var file_proto_mr_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x0b, 0x41,
	0x73, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x22, 0x92, 0x02, 0x0a, 0x0c, 0x41,
	0x73, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x4e,
	0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4e, 0x52,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x54, 0x61, 0x73,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x4d, 0x61, 0x70, 0x54,
	0x61, 0x73, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x4e, 0x75, 0x6d, 0x4f, 0x66,
	0x4d, 0x61, 0x70, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x3a, 0x0a, 0x18, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x18, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x52, 0x65, 0x64, 0x75,
	0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x4e, 0x75,
	0x6d, 0x4f, 0x66, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a,
	0x03, 0x45, 0x72, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x72, 0x72, 0x22,
	0x59, 0x0a, 0x0b, 0x4d, 0x61, 0x70, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x3a,
	0x0a, 0x18, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x18, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x20, 0x0a, 0x0c, 0x4d, 0x61,
	0x70, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x45, 0x72, 0x72, 0x22, 0x40, 0x0a, 0x0e,
	0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x23,
	0x0a, 0x0f, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x45, 0x72, 0x72, 0x22, 0x4d, 0x0a, 0x0d, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x03, 0x4e, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x03, 0x4e,
	0x6f, 0x77, 0x22, 0x10, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x2a, 0x2f, 0x0a, 0x08, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0f, 0x0a, 0x0b, 0x6d, 0x61, 0x70, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x10,
	0x00, 0x12, 0x12, 0x0a, 0x0e, 0x72, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x54,
	0x79, 0x70, 0x65, 0x10, 0x01, 0x2a, 0x57, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x0a, 0x69, 0x64, 0x6c, 0x65, 0x57, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x72,
	0x65, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x10, 0x03, 0x32, 0x8a,
	0x02, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x07,
	0x41, 0x73, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x15, 0x2e, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x73, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x16,
	0x2e, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x73, 0x6b, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x15, 0x2e, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x61, 0x70, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x16, 0x2e, 0x6d, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0a, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x12, 0x18, 0x2e, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x64, 0x75, 0x63, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x19, 0x2e, 0x6d,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x09, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x17, 0x2e, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x41, 0x72, 0x67, 0x73, 0x1a,
	0x18, 0x2e, 0x6d, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x6d, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_mr_proto_rawDescOnce sync.Once
	file_proto_mr_proto_rawDescData = file_proto_mr_proto_rawDesc
)

func file_proto_mr_proto_rawDescGZIP() []byte {
	file_proto_mr_proto_rawDescOnce.Do(func() {
		file_proto_mr_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_mr_proto_rawDescData)
	})
	return file_proto_mr_proto_rawDescData
}

var file_proto_mr_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_mr_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_mr_proto_goTypes = []interface{}{
	(TaskType)(0),                 // 0: mr.proto.TaskType
	(WorkerStatus)(0),             // 1: mr.proto.WorkerStatus
	(*AskTaskArgs)(nil),           // 2: mr.proto.AskTaskArgs
	(*AskTaskReply)(nil),          // 3: mr.proto.AskTaskReply
	(*MapTaskArgs)(nil),           // 4: mr.proto.MapTaskArgs
	(*MapTaskReply)(nil),          // 5: mr.proto.MapTaskReply
	(*ReduceTaskArgs)(nil),        // 6: mr.proto.ReduceTaskArgs
	(*ReduceTaskReply)(nil),       // 7: mr.proto.ReduceTaskReply
	(*HeartbeatArgs)(nil),         // 8: mr.proto.HeartbeatArgs
	(*HeartbeatReply)(nil),        // 9: mr.proto.HeartbeatReply
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_proto_mr_proto_depIdxs = []int32{
	0,  // 0: mr.proto.AskTaskReply.TaskType:type_name -> mr.proto.TaskType
	10, // 1: mr.proto.HeartbeatArgs.Now:type_name -> google.protobuf.Timestamp
	2,  // 2: mr.proto.MapReduce.AskTask:input_type -> mr.proto.AskTaskArgs
	4,  // 3: mr.proto.MapReduce.MapTask:input_type -> mr.proto.MapTaskArgs
	6,  // 4: mr.proto.MapReduce.ReduceTask:input_type -> mr.proto.ReduceTaskArgs
	8,  // 5: mr.proto.MapReduce.Heartbeat:input_type -> mr.proto.HeartbeatArgs
	3,  // 6: mr.proto.MapReduce.AskTask:output_type -> mr.proto.AskTaskReply
	5,  // 7: mr.proto.MapReduce.MapTask:output_type -> mr.proto.MapTaskReply
	7,  // 8: mr.proto.MapReduce.ReduceTask:output_type -> mr.proto.ReduceTaskReply
	9,  // 9: mr.proto.MapReduce.Heartbeat:output_type -> mr.proto.HeartbeatReply
	6,  // [6:10] is the sub-list for method output_type
	2,  // [2:6] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mr_proto_init() }
func file_proto_mr_proto_init() {
	if File_proto_mr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_mr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskTaskArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AskTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapTaskArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceTaskArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReduceTaskReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_mr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_mr_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mr_proto_goTypes,
		DependencyIndexes: file_proto_mr_proto_depIdxs,
		EnumInfos:         file_proto_mr_proto_enumTypes,
		MessageInfos:      file_proto_mr_proto_msgTypes,
	}.Build()
	File_proto_mr_proto = out.File
	file_proto_mr_proto_rawDesc = nil
	file_proto_mr_proto_goTypes = nil
	file_proto_mr_proto_depIdxs = nil
}
